### ISSUE TITLE
Subcommand watch fails when path to tectonic contains spaces

### ISSUE THREAD

**Issue by m-haug** [tectonic-typesetting/tectonic#1003]
It appears that the path to tectonic is not properly quoted before it is passed to the shell for execution in the watch command. See an example below. Note that I translated the actual error message because I was unable to change the UI language for the error message.

```shell
> tectonic -X watch
note: "version 2" Tectonic command-line interface activated
[Running `C:\Users\Markus Haug\scoop\apps\tectonic\current\tectonic.exe -X build`]
Command "C:\Users\Markus" could not be found.
[Finished running. Exit status: 0]
```

**Comment by xinslu** [comment]
I am unable to reproduce this on linux amd64. Might be localized to windows?

**Comment by m-haug** [comment]
I can no longer reproduce this under `v0.13.1` either. Perhaps it was fixed as part of upgrading `watchexec`? Either way, I will close this for now.

**Comment by m-haug** [comment]
I was too fast in closing: `tectonic -X watch` works fine, but `tectonic -X watch -x "build --open"` fails.

Checking [the code](https://github.com/tectonic-typesetting/tectonic/blob/ff9f29e960d370c39f5ec098be837ffcf2570c9b/src/bin/tectonic/v2cli.rs#L569), the former is run directly while the latter is wrapped in a shell.

**Comment by xinslu** [comment]
Able to replicate this case. I see the error should be a simple fix where I should be able to append the quotes around the tectonic location and should work. I would be able to push a fix right now.

**Comment by pkgw** [comment]
This should be fixed in 0.14.1, which I released the other day.

**Comment by m-haug** [comment]
Unfortunately, the issue persists with 0.14.1:

```shell
$ tectonic --version
Tectonic 0.14.1

$ tectonic -X watch -x "build --open"
note: "version 2" Tectonic command-line interface activated
[Running `"C:\Users\Markus Haug\scoop\apps\tectonic\current\tectonic.exe" -X build --open`]
Der Befehl "\"C:\Users\Markus Haug\scoop\apps\tectonic\current\tectonic.exe\"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
[Finished Running. Exit Status: 1]
```

Please excuse the German localization, I'm unable to change the locale for CMD. The error message roughly translates to “Command not found”.

I've dug a bit deeper, and it appears that the problem lies with `tokio` or `watchexec`'s usage thereof. I've run a series of commands to reproduce the format of the error message:

```batch
>uonsdu
Der Befehl "uonsdu" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Windows\System32>"uonsdu"
Der Befehl ""uonsdu"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Windows\System32>\"uonsdu"
Der Befehl "\"uonsdu"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Windows\System32>\"uonsdu\"
Der Befehl "\"uonsdu\"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

Apparently, the program name gets escaped somewhere down the stack. I will check the `tokio` docs next, file an issue elsewhere, and update here with progress.

**Comment by xinslu** [comment]
I see that you're using windows and my tests were conducted on a Linux system that seemed to work. I'm sorry I couldn't really test on a windows machine cuz I didn't really have access to one. Just as a sanity check to make sure I'm doing this right, could you try running this on a linux machine and making sure everything works as intended? Maybe could help narrow this issue down to a windows specific one.

**Comment by m-haug** [comment]
I don't have access to a Linux machine at the moment, but testing version 0.14.1 on WSL worked fine. That makes me pretty certain that the issue is specific to CMD/Windows.

There is also not a lot that tectonic can do about this, as the issue comes down to CMD parsing /C in a special way. This needs to be fixed in `watchexec`.
